title: "E-Values: From Statistics to ML"
description: "Workshop at Neural Information Processing Systems 2026 (Paris)"
description: "December 12th or 13th, 2026 (TBD)"
theme: jekyll-theme-cayman # Options: jekyll-theme-minimal, jekyll-theme-architect