title: "E-Values: From Statistics to ML"
#description: "Workshop at Neural Information Processing Systems 2026 (Paris)"
description: 'NeurIPS 2026 Workshop<span class="workshop-date">December 12 or 13, 2026 (TBD) · Paris, France</span>'
theme: jekyll-theme-cayman # Options: jekyll-theme-minimal, jekyll-theme-architect

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true